version: 1
length_min: 10
length_max: 100
width_min: 10
width_max: 100
area_min: 100
area_max: 10000
have_max: 5
area_max_claimable: 10000
priority: 1
# Updater config
updater:
  enabled: true
  downloadToPluginUpdateFolder: true
  targetUrl: 'https://github.com/joestrhq/ZoneMenu/releases/latest/download/'
  pomPropertiesFile: 'pom.properties'
  classifier: 'shaded'