name: ZoneMenu
version: ${project.version}
api-version: 1.13
description: ZoneMenu
author: joestr
authors: [2YB, 9YB]
website: https://github.com/joestr/ZoneMenu/wiki

main: xyz.joestr.zonemenu.ZoneMenu
database: false
depend: [WorldEdit, WorldGuard]

commands:
  zone:
    description: List all possible subcommands.
    #permission: zonemenu.*
    #permission-message: You need zonemenu.*.
    usage: /<command> [[addmember <zone> <player>]|cancel|create|[delete <zone>]|find|[flag <zone> <flag> <flagvalue>]|[info <zone>]|list|[removemember <zone> <player>]|[select <zone>]|[subcreate <zone>]|unselect>
    
permissions:
  zonemenu.*:
    description: Permission to list all possible sub-commands.
    default: true
    #children:
    #  zonemenu.*: true